---
title: "R Basic"
author: "Bourbon0212"
date: "2018/7/4"
output: html_document
---
* [Introduction to R](#1)
    + [運算](#1.1)
    + [變數](#1.2)
    + [向量](#1.3)
    + [矩陣](#1.4)
    + [因素向量](#1.5)
    + [資料框](#1.6)
    
* [Intermediate R](#2)
* [Introduction to the tidyverse](#3)

<h2 id = '1'></h2>
# Introduction to R

<h3 id = '1.1'></h3>
## 運算

```{r eval=TRUE}
3 + 3 #加法
3 - 3 #減法
3 * 3 #乘法
3 / 3 #除法
3 %% 3 #餘數
```

<h3 id = '1.2'></h3>
## 變數

變數種類：    
```{r eval=TRUE}
class(3.5)   
class(3L) #Capital 'L' after an integer forces it to be stored as an integer.
class(TRUE)    
class('R studio')    
```
變數運算：
```{r error=TRUE}
3.5 + 3L
3.5 + 'three'
```
不同型別的變數型態之間的某些操作是不被允許的，例如數字與字串相加。

<h3 id = '1.3'></h3>
## 向量
向量運算：
```{r}
vector1 <- c(100,300,500)
vector2 <- c(200,200,-100)
vector3 <- vector1 + vector2 #向量能直接進行運算
total <- sum(vector3) #使用sum向量加總
mean <- mean(vector3) #使用mean計算平均值
vector3
total
mean
```
向量命名：
```{r}
names(vector3) <- c('America','England','Japan') #用names替向量命名
vector3
```
向量選取：
```{r}
selection <- vector3 > 350
selection #直接比大小回傳邏輯值
select_vec1 <- vector3[selection] #使用中括號進行選取
select_vec1
select_vec2 <- vector3[1:2] #也能以引數位置選取，注意1是第一項。
select_vec2
```

<h3 id = '1.4'></h3>
## 矩陣
建立矩陣：
```{r}
#星際大戰票房
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)
#宣告 box_office
box_office <- c(new_hope, empire_strikes, return_jedi)
#建立 star_wars_matrix
star_wars_matrix <- matrix(box_office, byrow = T, nrow = 3) 
#一個具有 3 列(narrow = 3)的矩陣，數值(box_office)依序以列(byrow = TRUE)方向填入
star_wars_matrix
```
矩陣命名：
```{r}
#用來命名的向量 region 與 titles
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")
#colnames是欄命名function
colnames(star_wars_matrix) <- region
#rownames是列命名function
rownames(star_wars_matrix) <- titles
star_wars_matrix
```
運算合併：
```{r}
#rowSums列總和(colSums欄總和)
worldwide <- rowSums(star_wars_matrix)
#cbind欄合併(rbind列合併)
all_wars_matrix <- cbind(star_wars_matrix, worldwide)
all_wars_matrix
```
矩陣選取：
使用[列,欄]，來選取，連續選取以冒號連結，全選留白。
```{r}
#選出全部電影的非美國票房收入
non_us_all <- all_wars_matrix[,2]
non_us_all
#選出前兩部電影的非美國票房收入
non_us_some <- all_wars_matrix[1:2,2]
non_us_some
```

<h3 id = '1.5'></h3>
## 因素向量
因素向量是用來儲存類別型變數的統計資料，類別型變數與連續型變數最主要的差異在於類別型變數有類別個數的上限，而連續型變數則會有無窮多的個數。用factor顯示級別。
```{r}
#無法在類別之間比較好壞的【名目類別型變數】，如：動物。
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
factor_animals_vector

#天生有比較特性的【順序類別型變數】，如：溫度。
temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector
```
級別命名：
```{r}
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
#使用levels重新命名級別，，預設以字母排序
levels(factor_survey_vector) <- c('Female', 'Male')
factor_survey_vector
#使用summary產出摘要，注意summary(survey_vector)結果不同
summary(survey_vector)
summary(factor_survey_vector)
```
選取比較：
```{r}
#使用factor建立順序類別
speed_vector <- c("fast", "slow", "slow", "fast", "insane")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels = c("slow", "fast", "insane"))
#選出資料
da2 <- factor_speed_vector[2]
da5 <- factor_speed_vector[5]
#資料分析師 2 是否比資料分析師 5 快？
da2 > da5
```

<h3 id = '1.6'></h3>
## 資料框