if(!require(xml2))install.packages("xml2",repos = "http://cran.us.r-project.org")
if(!require(tmcn))install.packages("tmcn",repos = "http://cran.us.r-project.org")
if(!require(NLP))install.packages("NLP",repos = "http://cran.us.r-project.org")
if(!require(tm))install.packages("tm",repos = "http://cran.us.r-project.org")
if(!require(jiebaR))install.packages("jiebaR",repos = "http://cran.us.r-project.org")
if(!require(jiebaRD))install.packages("jiebaRD",repos = "http://cran.us.r-project.org")
if(!require(RColorBrewer))install.packages("RColorBrewer",repos = "http://cran.us.r-project.org")
if(!require(wordcloud))install.packages("wordcloud",repos = "http://cran.us.r-project.org")
if(!require(rvest))install.packages("rvest",repos = "http://cran.us.r-project.org")

library(tmcn)
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
library(rvest)
library(xml2)

library(tm)
rm(list=ls(all.names = TRUE))
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "用")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "這個")
docs <- tm_map(docs, toSpace, "因為")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "那")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "大家")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "話")
docs <- tm_map(docs, toSpace, "當然")
docs <- tm_map(docs, toSpace, "對")
docs <- tm_map(docs, toSpace, "或")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "簽名檔")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "玩")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "等")
docs <- tm_map(docs, toSpace, "上")
docs <- tm_map(docs, toSpace, "應該")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "比較")
docs <- tm_map(docs, toSpace, "自己")
docs <- tm_map(docs, toSpace, "編輯")
docs <- tm_map(docs, toSpace, "才")
docs <- tm_map(docs, toSpace, "能")
docs <- tm_map(docs, toSpace, "知道")
docs <- tm_map(docs, toSpace, "現")
#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs

library(jiebaR)
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")

library(wordcloud)
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)